-- schema_oracle.sql
-- Oracle 19c compatible schema translated from schema.sql

CREATE TABLE dams (
    dam_id VARCHAR2(20) PRIMARY KEY,
    dam_name VARCHAR2(255) NOT NULL,
    full_volume NUMBER(10, 0),
    latitude NUMBER(10, 6),
    longitude NUMBER(10, 6)
);

CREATE TABLE latest_data (
    dam_id VARCHAR2(20) PRIMARY KEY,
    dam_name VARCHAR2(255) NOT NULL,
    date_value DATE NOT NULL,
    storage_volume NUMBER(10, 3),
    percentage_full NUMBER(6, 2),
    storage_inflow NUMBER(10, 3),
    storage_release NUMBER(10, 3),
    FOREIGN KEY (dam_id) REFERENCES dams(dam_id)
);

CREATE TABLE dam_resources (
    resource_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dam_id VARCHAR2(20) NOT NULL,
    date_value DATE NOT NULL,
    storage_volume NUMBER(10, 3),
    percentage_full NUMBER(6, 2),
    storage_inflow NUMBER(10, 3),
    storage_release NUMBER(10, 3),
    FOREIGN KEY (dam_id) REFERENCES dams(dam_id)
);

CREATE TABLE specific_dam_analysis (
    dam_id VARCHAR2(20),
    analysis_date DATE,
    avg_storage_volume_12_months NUMBER(10, 3),
    avg_storage_volume_5_years NUMBER(10, 3),
    avg_storage_volume_10_years NUMBER(10, 3),
    avg_percentage_full_12_months NUMBER(6, 2),
    avg_percentage_full_5_years NUMBER(6, 2),
    avg_percentage_full_10_years NUMBER(6, 2),
    avg_storage_inflow_12_months NUMBER(10, 3),
    avg_storage_inflow_5_years NUMBER(10, 3),
    avg_storage_inflow_10_years NUMBER(10, 3),
    avg_storage_release_12_months NUMBER(10, 3),
    avg_storage_release_5_years NUMBER(10, 3),
    avg_storage_release_10_years NUMBER(10, 3),
    PRIMARY KEY (dam_id, analysis_date),
    FOREIGN KEY (dam_id) REFERENCES dams(dam_id)
);

CREATE TABLE overall_dam_analysis (
    analysis_date DATE PRIMARY KEY,
    avg_storage_volume_12_months NUMBER(10, 3),
    avg_storage_volume_5_years NUMBER(10, 3),
    avg_storage_volume_10_years NUMBER(10, 3),
    avg_percentage_full_12_months NUMBER(6, 2),
    avg_percentage_full_5_years NUMBER(6, 2),
    avg_percentage_full_10_years NUMBER(6, 2),
    avg_storage_inflow_12_months NUMBER(10, 3),
    avg_storage_inflow_5_years NUMBER(10, 3),
    avg_storage_inflow_10_years NUMBER(10, 3),
    avg_storage_release_12_months NUMBER(10, 3),
    avg_storage_release_5_years NUMBER(10, 3),
    avg_storage_release_10_years NUMBER(10, 3)
);

CREATE TABLE dam_groups (
    group_name VARCHAR2(255) PRIMARY KEY
);

CREATE TABLE dam_group_members (
    group_name VARCHAR2(255) NOT NULL,
    dam_id VARCHAR2(20) NOT NULL,
    PRIMARY KEY (group_name, dam_id),
    FOREIGN KEY (group_name) REFERENCES dam_groups(group_name),
    FOREIGN KEY (dam_id) REFERENCES dams(dam_id)
);
